### ISSUE TITLE
Telemetry installation setting for multi-engine node cluster setup

### ISSUE THREAD

**Issue by Ankit-K-Gupta** [eapowertools-archive/qs-telemetry-dashboard-node#105]
HI Levi,

Thanks for creating the dashboard and publishing it on Github. We are using it to troubleshoot the performance issues in our system. 
I have successfully installed, configured and used Telemetry dashboard in my single node Qlik Sense setup.
But in a multi node (wit multiple engine nodes) Qlik Sense cluster setup , how to install and configure Telemetry dashboard. The reason for asking this is to understand how Telemetry tasks will reload metadata and needed information for all engine node with only one data connection named "EngineSettingsFolder" which gets created at the time of installation.  How it will collect the data for other engine nodes.

Regards
Ankit

**Comment by levi-turner** [comment]
Hey there,

I'd be remiss to take credit for all of this. There's been heavy lifting by a number of folks like @jparis and others. Let's start out with an outline for the sources for the dashboard:

| Data Connection  |  Default Path |  Needs Multi-Node Config? |
|---|---|---|
| `ArchivedLogsFolder`  | `YourQlikSharePath\ArchivedLogs`  |  No |
| `EngineSettingsFolder`  | `C:\ProgramData\Qlik\Sense\Engine\`  | Mayyyybe, for now, no for the next release  |
| `ServerLogFolder`  | `C:\ProgramData\Qlik\Sense\Log\`  | Sort of, but not necessarily  |
| `TelemetryMetadata`  | `YourQlikSharePath\TelemetryDashboard\MetadataOutput\`  |  No |

So we only have two to focus on: `EngineSettingsFolder` and `ServerLogFolder`.

For `EngineSettingsFolder`, this pulls in the configured thresholds for Telemetry. At the outset, this *only* matters at all if you have different thresholds configured in the `Settings.ini` for different nodes. If you don't then the existing method does not matter. That being said, I have a new method in the version of the app that @jparis and I are working on which does this dynamically without the need for this data connection. Since this data is not exposed via APIs, I need to go through parsing the underlying Qlik logs for this. My method will be something like this:

```
//******************************************************
// Load Engine Service Logs from the ArchivedLogFolder directory (all nodes)
//******************************************************
sub QIXSettingLoad(Root)
    for each FileExtension in '*.log'
		for each FoundFile in filelist (Root&'\*_Service_Engine*' & FileExtension)
            IF round(num(date(today())-date(FileTime('$(FoundFile)')))) <= '$(v#LogDays)' then
                tmp2:
                LOAD 
                	"Timestamp",
                    Hostname,
    				//Message,
                    if([Message] like '*Current setting for ErrorPeakMemory*', num(TextBetween([Message],'Current setting for ErrorPeakMemory=', ',')), null()) AS [ErrorPeakMemorytmp],
                    if([Message] like '*Current setting for ErrorProcessTimeMs*', num(TextBetween([Message],'Current setting for ErrorProcessTimeMs=', ',')), null()) AS [ErrorProcessTimetmp],
                    if([Message] like '*Current setting for WarningPeakMemory*', num(TextBetween([Message],'Current setting for WarningPeakMemory=', ',')), null()) AS [WarningPeakMemorytmp],
                    if([Message] like '*Current setting for WarningProcessTimeMs*', num(TextBetween([Message],'Current setting for WarningProcessTimeMs=', ',')), null()) AS [WarningProcessTimetmp],
                    FileTime() AS [FileTime]
                FROM
                '$(FoundFile)' (txt, utf8, embedded labels, delimiter is '\t', msq); 
             End If
        next FoundFile
    next FileExtension
		for each SubDirectory in dirlist( Root & '\*' )
			call QIXSettingLoad(SubDirectory)
		next SubDirectory
end sub

Call QIXSettingLoad('$(vLogArchive)') ;
```

With `ServerLogFolder`, the default value is a local path (`C:\...`) which would be evaluated on a per node basis depending on which node is doing the reload. For coverage of the active logs on all nodes, This behavior can be adjusted in the load script and it's documented here: https://www.youtube.com/watch?v=iLKOpnKbLJg . Is this needed? Only if you expect to analyze results which occurred recently. Logs are archived on a cadence of every 12 hours / 8MB / service restart (https://support.qlik.com/articles/000027218). Functionally for most customers this optional configuration isn't needed. But the capability is there should the need arise.

**Comment by rzenere-synthese** [comment]
Hey @levi-turner , 
since you mentioned next release... Do you have any eta for its release?

Thank you

**Comment by jparis** [comment]
That's actually my bad, and no we do not at this time. Definitely before the end of the year.

**Comment by jparis** [comment]
Official release coming very soon: https://github.com/eapowertools/qs-telemetry-dashboard
